### ISSUE TITLE
Generate CCDA file in java using MDHT

### ISSUE THREAD

**Issue by jagdeepsmartdata** [mdht/mdht-models#105]
Hi,

I am working on java project. I need to implement MDHT library to parse ccda. I can not find step by step documentation regarding implementation of MDHT in java. I am using eclipse ide. It would be great if you can provide step by step solution.
I have already gone through the following and its related link, but nothing is helpful.
https://www.projects.openhealthtools.org/sf/projects/mdht/

Thanks
Jagdeep

**Comment by shivasish06** [comment]
Hi jagdeep,
This [link](http://www.cdatools.com/) might be helpful .
