### ISSUE TITLE
Validation WAR source code and License

### ISSUE THREAD

**Issue by lartkma** [mdht/mdht-models#115]
My current company wants to use the MDHT. We checked the validation WAR (replacing inner JARs with the latest version) and concluded that it's what we need. However, we need it in an slightly different form. We peeked out the WAR file with a decompiler and checked how the library is used and the output is made.

We want to use some methods of the code (to get the same output), but I was concerned for the licencing aspects. I've haven't found the source code and neither have found the license used. It is EPL 1 .0 like the MDHT itself? What is needed to use those parts of the WAR code?

**Comment by swmuir** [comment]
Can you explain the slightly different form you need  ?

As far as the license it is all EPL

thanks

Sean

**Comment by drbgfc** [comment]
I wrote the MDHT validation WAR you are referring to in a quick a dirty fashion hence not releasing the source specifically. However, all of it is open for use by anyone who wants to (even if derived by decompiling). Copy and paste is fine with me. If you'd like to check out a more carefully crafted version look at the open source project myself and others have been working on here: https://github.com/siteadmin/reference-ccda-validator/. You may not want to use it, but, it should have good pointers for implementation and is far more up-to-date. Here is the most relevant location for your purposes https://github.com/siteadmin/reference-ccda-validator/blob/develop/src/main/java/org/sitenv/referenceccda/validators/schema/ReferenceCCDAValidator.java
